# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-21 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1042, null=True, verbose_name='地址')),
                ('url1', models.CharField(blank=True, max_length=1042, null=True, verbose_name='地址1')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('time_create', models.DateField(auto_now_add=True, help_text='格式yyyy-mm-dd', null=True, verbose_name='创建时间')),
                ('time_update', models.DateField(auto_now_add=True, help_text='格式yyyy-mm-dd', null=True, verbose_name='更新时间')),
                ('type', models.CharField(blank=True, choices=[('phone', '手机端'), ('PC', 'PC端')], max_length=256, null=True, verbose_name='图片类型')),
                ('_status', models.CharField(blank=True, max_length=256, null=True)),
                ('copyright', models.CharField(blank=True, choices=[('legal', '正版'), ('pirate', '盗版')], max_length=256, null=True, verbose_name='版权')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='用户名')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=256, null=True, verbose_name='手机号')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1042, null=True, verbose_name='地址')),
                ('url1', models.CharField(blank=True, max_length=1042, null=True, verbose_name='地址1')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('time_create', models.DateField(auto_now_add=True, help_text='格式yyyy-mm-dd', null=True, verbose_name='创建时间')),
                ('time_update', models.DateField(auto_now_add=True, help_text='格式yyyy-mm-dd', null=True, verbose_name='更新时间')),
                ('type', models.CharField(blank=True, choices=[('phone', '手机端'), ('PC', 'PC端')], max_length=256, null=True, verbose_name='图片类型')),
                ('_status', models.CharField(blank=True, max_length=256, null=True)),
                ('copyright', models.CharField(blank=True, choices=[('legal', '正版'), ('pirate', '盗版')], max_length=256, null=True, verbose_name='版权')),
            ],
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic_vid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dis.Videos', verbose_name='视频'),
        ),
    ]
