# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-18 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dis', '0002_auto_20190917_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=16, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
