# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-18 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dis', '0003_auto_20190918_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='password',
            field=models.CharField(max_length=16, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
