# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-18 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dis', '0004_auto_20190918_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
