# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-18 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dis', '0005_delete_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_reg',
            new_name='User',
        ),
    ]
