# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-20 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dis', '0006_auto_20190918_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1042, null=True, verbose_name='地址')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('time_create', models.DateField(default=None, help_text='格式yyyy-mm-dd', verbose_name='创建时间')),
                ('time_update', models.DateField(auto_now_add=True, help_text='格式yyyy-mm-dd', verbose_name='更新时间')),
                ('type', models.CharField(blank=True, choices=[('all', '全部'), ('phone', '手机端'), ('PC', 'PC端')], default='male', max_length=256, null=True, verbose_name='图片类型')),
                ('_status', models.CharField(blank=True, max_length=256, null=True)),
                ('copyright', models.CharField(blank=True, choices=[('legal', '正版'), ('pirate', '盗版')], default='male', max_length=256, null=True, verbose_name='版权')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1042, null=True, verbose_name='地址')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('time_create', models.DateField(default=None, help_text='格式yyyy-mm-dd', verbose_name='创建时间')),
                ('time_update', models.DateField(auto_now_add=True, help_text='格式yyyy-mm-dd', verbose_name='更新时间')),
                ('type', models.CharField(blank=True, choices=[('all', '全部'), ('phone', '手机端'), ('PC', 'PC端')], default='male', max_length=256, null=True, verbose_name='图片类型')),
                ('_status', models.CharField(blank=True, max_length=256, null=True)),
                ('copyright', models.CharField(blank=True, choices=[('legal', '正版'), ('pirate', '盗版')], default='male', max_length=256, null=True, verbose_name='版权')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='用户名'),
        ),
    ]
