# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-20 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dis', '0010_auto_20190920_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='pic_vid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dis.Videos', verbose_name='视频'),
        ),
    ]
