# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-20 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dis', '0011_pictures_pic_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pic_vid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Dis.Videos', verbose_name='视频'),
        ),
    ]
