# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-20 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dis', '0012_auto_20190920_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pic_vid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dis.Videos', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='type',
            field=models.CharField(blank=True, choices=[('phone', '手机端'), ('PC', 'PC端')], default='male', max_length=256, null=True, verbose_name='图片类型'),
        ),
    ]
