# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-20 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dis', '0013_auto_20190920_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='url1',
            field=models.CharField(blank=True, max_length=1042, null=True, verbose_name='地址1'),
        ),
        migrations.AddField(
            model_name='videos',
            name='url1',
            field=models.CharField(blank=True, max_length=1042, null=True, verbose_name='地址1'),
        ),
    ]
