# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-20 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dis', '0014_auto_20190920_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='type',
            field=models.CharField(blank=True, choices=[('phone', '手机端'), ('PC', 'PC端')], default='male', max_length=256, null=True, verbose_name='图片类型'),
        ),
    ]
