# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-20 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dis', '0017_auto_20190920_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='copyright',
            field=models.CharField(blank=True, choices=[('legal', '正版'), ('pirate', '盗版')], max_length=256, null=True, verbose_name='版权'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='copyright',
            field=models.CharField(blank=True, choices=[('legal', '正版'), ('pirate', '盗版')], max_length=256, null=True, verbose_name='版权'),
        ),
    ]
